### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by nakulcr7** [thebrain22/Speaking-With-Leap#1]
Hello,

How do I make this project work? I did read the readme.md, but didn't understand.

Thank you

**Comment by gammison** [comment]
Sorry, I forgot to add a few jars that are needed. You will need the FreeTTS jars included at http://freetts.sourceforge.net/docs/index.php, follow project instructions there for project setup. You must also install the leap motion sdk. Follow the setup instructions for a java project on the leap motion website https://developer.leapmotion.com/documentation/java/devguide/Project_Setup.html . I used the eclipse setup method.
I will add this to the read.md

**Comment by nakulcr7** [comment]
Hey, I did the following according to your instructions.
1. Followed the 'Eclipse' instructions on the leap motion website
2. Replaced the folders in the Eclipse workspace with those of your project
3. Downloaded the freetts 'bin' folder and put the lib/freetts.jar into the project folder
4. Executed the TextToSpeech.exe

It still didn't work. I've attached the images of the project folder and the terminal results. 

Please have a look and help me out

Thank you

![2015-03-24 02 29 39 pm](https://cloud.githubusercontent.com/assets/5729612/6798354/3b92d832-d232-11e4-9657-f6c33528a861.png)
